"""Add generation_duration to Summary

Revision ID: 2d46f5180778
Revises: b5a3a0e28866
Create Date: 2026-02-07 15:19:34.398877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d46f5180778'
down_revision = 'b5a3a0e28866'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('summary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('generation_duration', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('summary', schema=None) as batch_op:
        batch_op.drop_column('generation_duration')

    # ### end Alembic commands ###
